#
# OpenSSL/crypto/bn/Makefile
#

DIR=	bn
TOP=	../..
CC=	cc
CPP=    $(CC) -E
INCLUDES= -I.. -I$(TOP) -I../../include
CFLAG=-g
MAKEFILE=	Makefile
AR=		ar r

BN_ASM=		bn_asm.o

CFLAGS= $(INCLUDES) $(CFLAG)
ASFLAGS= $(INCLUDES) $(ASFLAG)
AFLAGS= $(ASFLAGS)

GENERAL=Makefile
TEST=bntest.c exptest.c
APPS=

LIB=$(TOP)/libcrypto.a
LIBSRC=	bn_add.c bn_div.c bn_exp.c bn_lib.c bn_ctx.c bn_mul.c bn_mod.c \
	bn_print.c bn_rand.c bn_shift.c bn_word.c bn_blind.c \
	bn_kron.c bn_sqrt.c bn_gcd.c bn_prime.c bn_err.c bn_sqr.c bn_asm.c \
	bn_recp.c bn_mont.c bn_mpi.c bn_exp2.c bn_gf2m.c bn_nist.c \
	bn_depr.c bn_const.c bn_x931p.c

LIBOBJ=	bn_add.o bn_div.o bn_exp.o bn_lib.o bn_ctx.o bn_mul.o bn_mod.o \
	bn_print.o bn_rand.o bn_shift.o bn_word.o bn_blind.o \
	bn_kron.o bn_sqrt.o bn_gcd.o bn_prime.o bn_err.o bn_sqr.o $(BN_ASM) \
	bn_recp.o bn_mont.o bn_mpi.o bn_exp2.o bn_gf2m.o bn_nist.o \
	bn_depr.o bn_const.o bn_x931p.o

SRC= $(LIBSRC)

EXHEADER= bn.h
HEADER=	bn_lcl.h bn_prime.h $(EXHEADER)

ALL=    $(GENERAL) $(SRC) $(HEADER)

top:
	(cd ../..; $(MAKE) DIRS=crypto SDIRS=$(DIR) sub_all)

all:	lib

bn_prime.h: bn_prime.pl
	$(PERL) bn_prime.pl >bn_prime.h

divtest: divtest.c ../../libcrypto.a
	cc -I../../include divtest.c -o divtest ../../libcrypto.a

bnbug: bnbug.c ../../libcrypto.a top
	cc -g -I../../include bnbug.c -o bnbug ../../libcrypto.a

lib:	$(LIBOBJ)
	$(AR) $(LIB) $(LIBOBJ)
	$(RANLIB) $(LIB) || echo Never mind.
	@touch lib

bn-586.s:	asm/bn-586.pl ../perlasm/x86asm.pl
	$(PERL) asm/bn-586.pl $(PERLASM_SCHEME) $(CFLAGS) $(PROCESSOR) > $@
co-586.s:	asm/co-586.pl ../perlasm/x86asm.pl
	$(PERL) asm/co-586.pl $(PERLASM_SCHEME) $(CFLAGS) $(PROCESSOR) > $@
x86-mont.s:	asm/x86-mont.pl ../perlasm/x86asm.pl
	$(PERL) asm/x86-mont.pl $(PERLASM_SCHEME) $(CFLAGS) $(PROCESSOR) > $@
x86-gf2m.s:	asm/x86-gf2m.pl ../perlasm/x86asm.pl
	$(PERL) asm/x86-gf2m.pl $(PERLASM_SCHEME) $(CFLAGS) $(PROCESSOR) > $@

sparcv8.o:	asm/sparcv8.S
	$(CC) $(CFLAGS) -c asm/sparcv8.S
bn-sparcv9.o:	asm/sparcv8plus.S
	$(CC) $(CFLAGS) -c -o $@ asm/sparcv8plus.S
sparcv9a-mont.s:	asm/sparcv9a-mont.pl
	$(PERL) asm/sparcv9a-mont.pl $(CFLAGS) > $@
sparcv9-mont.s:		asm/sparcv9-mont.pl
	$(PERL) asm/sparcv9-mont.pl $(CFLAGS) > $@

bn-mips3.o:	asm/mips3.s
	@if [ "$(CC)" = "gcc" ]; then \
		ABI=`expr "$(CFLAGS)" : ".*-mabi=\([n3264]*\)"` && \
		as -$$ABI -O -o $@ asm/mips3.s; \
	else	$(CC) -c $(CFLAGS) -o $@ asm/mips3.s; fi

bn-mips.s:	asm/mips.pl
	$(PERL) asm/mips.pl $(PERLASM_SCHEME) $@
mips-mont.s:	asm/mips-mont.pl
	$(PERL)	asm/mips-mont.pl $(PERLASM_SCHEME) $@

bn-s390x.o:	asm/s390x.S
	$(CC) $(CFLAGS) -c -o $@ asm/s390x.S
s390x-gf2m.s:	asm/s390x-gf2m.pl
	$(PERL) asm/s390x-gf2m.pl $(PERLASM_SCHEME) $@

x86_64-gcc.o:	asm/x86_64-gcc.c
	$(CC) $(CFLAGS) -c -o $@ asm/x86_64-gcc.c
x86_64-mont.s:	asm/x86_64-mont.pl
	$(PERL) asm/x86_64-mont.pl $(PERLASM_SCHEME) > $@
x86_64-mont5.s:	asm/x86_64-mont5.pl
	$(PERL) asm/x86_64-mont5.pl $(PERLASM_SCHEME) > $@
x86_64-gf2m.s:	asm/x86_64-gf2m.pl
	$(PERL) asm/x86_64-gf2m.pl $(PERLASM_SCHEME) > $@
modexp512-x86_64.s:	asm/modexp512-x86_64.pl
	$(PERL) asm/modexp512-x86_64.pl $(PERLASM_SCHEME) > $@

bn-ia64.s:	asm/ia64.S
	$(CC) $(CFLAGS) -E asm/ia64.S > $@
ia64-mont.s:	asm/ia64-mont.pl
	$(PERL) asm/ia64-mont.pl $@ $(CFLAGS)

# GNU assembler fails to compile PA-RISC2 modules, insist on calling
# vendor assembler...
pa-risc2W.o: asm/pa-risc2W.s
	/usr/ccs/bin/as -o pa-risc2W.o asm/pa-risc2W.s
pa-risc2.o: asm/pa-risc2.s
	/usr/ccs/bin/as -o pa-risc2.o asm/pa-risc2.s
parisc-mont.s:	asm/parisc-mont.pl
	$(PERL) asm/parisc-mont.pl $(PERLASM_SCHEME) $@

# ppc - AIX, Linux, MacOS X...
bn-ppc.s:	asm/ppc.pl;	$(PERL) asm/ppc.pl $(PERLASM_SCHEME) $@
ppc-mont.s:	asm/ppc-mont.pl;$(PERL) asm/ppc-mont.pl $(PERLASM_SCHEME) $@
ppc64-mont.s:	asm/ppc64-mont.pl;$(PERL) asm/ppc64-mont.pl $(PERLASM_SCHEME) $@

alpha-mont.s:	asm/alpha-mont.pl
	(preproc=/tmp/$$$$.$@; trap "rm $$preproc" INT; \
	$(PERL) asm/alpha-mont.pl > $$preproc && \
	$(CC) -E $$preproc > $@ && rm $$preproc)

# GNU make "catch all"
%-mont.s:	asm/%-mont.pl;	$(PERL) $< $(PERLASM_SCHEME) $@
%-gf2m.S:	asm/%-gf2m.pl;	$(PERL) $< $(PERLASM_SCHEME) $@

armv4-gf2m.o:	armv4-gf2m.S

files:
	$(PERL) $(TOP)/util/files.pl Makefile >> $(TOP)/MINFO

links:
	@$(PERL) $(TOP)/util/mklink.pl ../../include/openssl $(EXHEADER)
	@$(PERL) $(TOP)/util/mklink.pl ../../test $(TEST)
	@$(PERL) $(TOP)/util/mklink.pl ../../apps $(APPS)

install:
	@[ -n "$(INSTALLTOP)" ] # should be set by top Makefile...
	@headerlist="$(EXHEADER)"; for i in $$headerlist ; \
	do  \
	(cp $$i $(INSTALL_PREFIX)$(INSTALLTOP)/include/openssl/$$i; \
	chmod 644 $(INSTALL_PREFIX)$(INSTALLTOP)/include/openssl/$$i ); \
	done;

exptest:
	rm -f exptest
	gcc -I../../include -g2 -ggdb -o exptest exptest.c ../../libcrypto.a

div:
	rm -f a.out
	gcc -I.. -g div.c ../../libcrypto.a

tags:
	ctags $(SRC)

tests:

lint:
	lint -DLINT $(INCLUDES) $(SRC)>fluff

update: bn_prime.h depend

depend:
	@[ -n "$(MAKEDEPEND)" ] # should be set by upper Makefile...
	$(MAKEDEPEND) -- $(CFLAG) $(INCLUDES) $(DEPFLAG) -- $(PROGS) $(LIBSRC)

dclean:
	$(PERL) -pe 'if (/^# DO NOT DELETE THIS LINE/) {print; exit(0);}' $(MAKEFILE) >Makefile.new
	mv -f Makefile.new $(MAKEFILE)

clean:
	rm -f *.s *.o *.obj lib tags core .pure .nfs* *.old *.bak fluff

# DO NOT DELETE THIS LINE -- make depend depends on it.

bn_add.o: ../../e_os.h ../../include/openssl/bio.h ../../include/openssl/bn.h
bn_add.o: ../../include/openssl/buffer.h ../../include/openssl/crypto.h
bn_add.o: ../../include/openssl/e_os2.h ../../include/openssl/err.h
bn_add.o: ../../include/openssl/lhash.h ../../include/openssl/opensslconf.h
bn_add.o: ../../include/openssl/opensslv.h ../../include/openssl/ossl_typ.h
bn_add.o: ../../include/openssl/safestack.h ../../include/openssl/stack.h
bn_add.o: ../../include/openssl/symhacks.h ../../ms/applink.c ../../ms/uplink.h
bn_add.o: ../cryptlib.h bn_add.c bn_lcl.h c:\mingw\include\_mingw.h
bn_add.o: c:\mingw\include\basetsd.h c:\mingw\include\errno.h
bn_add.o: c:\mingw\include\fcntl.h c:\mingw\include\io.h
bn_add.o: c:\mingw\include\malloc.h c:\mingw\include\poppack.h
bn_add.o: c:\mingw\include\pshpack4.h c:\mingw\include\stdio.h
bn_add.o: c:\mingw\include\stdlib.h c:\mingw\include\string.h
bn_add.o: c:\mingw\include\sys\types.h c:\mingw\include\winbase.h
bn_add.o: c:\mingw\include\wincon.h c:\mingw\include\windef.h
bn_add.o: c:\mingw\include\windows.h c:\mingw\include\winerror.h
bn_add.o: c:\mingw\include\wingdi.h c:\mingw\include\winnetwk.h
bn_add.o: c:\mingw\include\winnls.h c:\mingw\include\winnt.h
bn_add.o: c:\mingw\include\winreg.h c:\mingw\include\winsock2.h
bn_add.o: c:\mingw\include\winsvc.h c:\mingw\include\winuser.h
bn_add.o: c:\mingw\include\winver.h c:\mingw\include\ws2tcpip.h
bn_add.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stdarg.h
bn_add.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stddef.h
bn_asm.o: ../../e_os.h ../../include/openssl/bio.h ../../include/openssl/bn.h
bn_asm.o: ../../include/openssl/buffer.h ../../include/openssl/crypto.h
bn_asm.o: ../../include/openssl/e_os2.h ../../include/openssl/err.h
bn_asm.o: ../../include/openssl/lhash.h ../../include/openssl/opensslconf.h
bn_asm.o: ../../include/openssl/opensslv.h ../../include/openssl/ossl_typ.h
bn_asm.o: ../../include/openssl/safestack.h ../../include/openssl/stack.h
bn_asm.o: ../../include/openssl/symhacks.h ../../ms/applink.c ../../ms/uplink.h
bn_asm.o: ../cryptlib.h bn_asm.c bn_lcl.h c:\mingw\include\_mingw.h
bn_asm.o: c:\mingw\include\assert.h c:\mingw\include\basetsd.h
bn_asm.o: c:\mingw\include\errno.h c:\mingw\include\fcntl.h
bn_asm.o: c:\mingw\include\io.h c:\mingw\include\malloc.h
bn_asm.o: c:\mingw\include\poppack.h c:\mingw\include\pshpack4.h
bn_asm.o: c:\mingw\include\stdio.h c:\mingw\include\stdlib.h
bn_asm.o: c:\mingw\include\string.h c:\mingw\include\sys\types.h
bn_asm.o: c:\mingw\include\winbase.h c:\mingw\include\wincon.h
bn_asm.o: c:\mingw\include\windef.h c:\mingw\include\windows.h
bn_asm.o: c:\mingw\include\winerror.h c:\mingw\include\wingdi.h
bn_asm.o: c:\mingw\include\winnetwk.h c:\mingw\include\winnls.h
bn_asm.o: c:\mingw\include\winnt.h c:\mingw\include\winreg.h
bn_asm.o: c:\mingw\include\winsock2.h c:\mingw\include\winsvc.h
bn_asm.o: c:\mingw\include\winuser.h c:\mingw\include\winver.h
bn_asm.o: c:\mingw\include\ws2tcpip.h
bn_asm.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stdarg.h
bn_asm.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stddef.h
bn_blind.o: ../../e_os.h ../../include/openssl/bio.h ../../include/openssl/bn.h
bn_blind.o: ../../include/openssl/buffer.h ../../include/openssl/crypto.h
bn_blind.o: ../../include/openssl/e_os2.h ../../include/openssl/err.h
bn_blind.o: ../../include/openssl/lhash.h ../../include/openssl/opensslconf.h
bn_blind.o: ../../include/openssl/opensslv.h ../../include/openssl/ossl_typ.h
bn_blind.o: ../../include/openssl/safestack.h ../../include/openssl/stack.h
bn_blind.o: ../../include/openssl/symhacks.h ../../ms/applink.c
bn_blind.o: ../../ms/uplink.h ../cryptlib.h bn_blind.c bn_lcl.h
bn_blind.o: c:\mingw\include\_mingw.h c:\mingw\include\basetsd.h
bn_blind.o: c:\mingw\include\errno.h c:\mingw\include\fcntl.h
bn_blind.o: c:\mingw\include\io.h c:\mingw\include\malloc.h
bn_blind.o: c:\mingw\include\poppack.h c:\mingw\include\pshpack4.h
bn_blind.o: c:\mingw\include\stdio.h c:\mingw\include\stdlib.h
bn_blind.o: c:\mingw\include\string.h c:\mingw\include\sys\types.h
bn_blind.o: c:\mingw\include\winbase.h c:\mingw\include\wincon.h
bn_blind.o: c:\mingw\include\windef.h c:\mingw\include\windows.h
bn_blind.o: c:\mingw\include\winerror.h c:\mingw\include\wingdi.h
bn_blind.o: c:\mingw\include\winnetwk.h c:\mingw\include\winnls.h
bn_blind.o: c:\mingw\include\winnt.h c:\mingw\include\winreg.h
bn_blind.o: c:\mingw\include\winsock2.h c:\mingw\include\winsvc.h
bn_blind.o: c:\mingw\include\winuser.h c:\mingw\include\winver.h
bn_blind.o: c:\mingw\include\ws2tcpip.h
bn_blind.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stdarg.h
bn_blind.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stddef.h
bn_const.o: ../../include/openssl/crypto.h ../../include/openssl/e_os2.h
bn_const.o: ../../include/openssl/opensslconf.h
bn_const.o: ../../include/openssl/opensslv.h ../../include/openssl/ossl_typ.h
bn_const.o: ../../include/openssl/safestack.h ../../include/openssl/stack.h
bn_const.o: ../../include/openssl/symhacks.h bn.h bn_const.c
bn_const.o: c:\mingw\include\_mingw.h c:\mingw\include\stdio.h
bn_const.o: c:\mingw\include\stdlib.h c:\mingw\include\sys\types.h
bn_const.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stdarg.h
bn_const.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stddef.h
bn_ctx.o: ../../e_os.h ../../include/openssl/bio.h ../../include/openssl/bn.h
bn_ctx.o: ../../include/openssl/buffer.h ../../include/openssl/crypto.h
bn_ctx.o: ../../include/openssl/e_os2.h ../../include/openssl/err.h
bn_ctx.o: ../../include/openssl/lhash.h ../../include/openssl/opensslconf.h
bn_ctx.o: ../../include/openssl/opensslv.h ../../include/openssl/ossl_typ.h
bn_ctx.o: ../../include/openssl/safestack.h ../../include/openssl/stack.h
bn_ctx.o: ../../include/openssl/symhacks.h ../../ms/applink.c ../../ms/uplink.h
bn_ctx.o: ../cryptlib.h bn_ctx.c bn_lcl.h c:\mingw\include\_mingw.h
bn_ctx.o: c:\mingw\include\assert.h c:\mingw\include\basetsd.h
bn_ctx.o: c:\mingw\include\errno.h c:\mingw\include\fcntl.h
bn_ctx.o: c:\mingw\include\io.h c:\mingw\include\malloc.h
bn_ctx.o: c:\mingw\include\poppack.h c:\mingw\include\pshpack4.h
bn_ctx.o: c:\mingw\include\stdio.h c:\mingw\include\stdlib.h
bn_ctx.o: c:\mingw\include\string.h c:\mingw\include\sys\types.h
bn_ctx.o: c:\mingw\include\winbase.h c:\mingw\include\wincon.h
bn_ctx.o: c:\mingw\include\windef.h c:\mingw\include\windows.h
bn_ctx.o: c:\mingw\include\winerror.h c:\mingw\include\wingdi.h
bn_ctx.o: c:\mingw\include\winnetwk.h c:\mingw\include\winnls.h
bn_ctx.o: c:\mingw\include\winnt.h c:\mingw\include\winreg.h
bn_ctx.o: c:\mingw\include\winsock2.h c:\mingw\include\winsvc.h
bn_ctx.o: c:\mingw\include\winuser.h c:\mingw\include\winver.h
bn_ctx.o: c:\mingw\include\ws2tcpip.h
bn_ctx.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stdarg.h
bn_ctx.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stddef.h
bn_depr.o: ../../e_os.h ../../include/openssl/bio.h ../../include/openssl/bn.h
bn_depr.o: ../../include/openssl/buffer.h ../../include/openssl/crypto.h
bn_depr.o: ../../include/openssl/e_os2.h ../../include/openssl/err.h
bn_depr.o: ../../include/openssl/lhash.h ../../include/openssl/opensslconf.h
bn_depr.o: ../../include/openssl/opensslv.h ../../include/openssl/ossl_typ.h
bn_depr.o: ../../include/openssl/rand.h ../../include/openssl/safestack.h
bn_depr.o: ../../include/openssl/stack.h ../../include/openssl/symhacks.h
bn_depr.o: ../../ms/applink.c ../../ms/uplink.h ../cryptlib.h bn_depr.c
bn_depr.o: bn_lcl.h c:\mingw\include\_mingw.h c:\mingw\include\basetsd.h
bn_depr.o: c:\mingw\include\errno.h c:\mingw\include\fcntl.h
bn_depr.o: c:\mingw\include\io.h c:\mingw\include\malloc.h
bn_depr.o: c:\mingw\include\poppack.h c:\mingw\include\pshpack4.h
bn_depr.o: c:\mingw\include\stdio.h c:\mingw\include\stdlib.h
bn_depr.o: c:\mingw\include\string.h c:\mingw\include\sys\types.h
bn_depr.o: c:\mingw\include\time.h c:\mingw\include\winbase.h
bn_depr.o: c:\mingw\include\wincon.h c:\mingw\include\windef.h
bn_depr.o: c:\mingw\include\windows.h c:\mingw\include\winerror.h
bn_depr.o: c:\mingw\include\wingdi.h c:\mingw\include\winnetwk.h
bn_depr.o: c:\mingw\include\winnls.h c:\mingw\include\winnt.h
bn_depr.o: c:\mingw\include\winreg.h c:\mingw\include\winsock2.h
bn_depr.o: c:\mingw\include\winsvc.h c:\mingw\include\winuser.h
bn_depr.o: c:\mingw\include\winver.h c:\mingw\include\ws2tcpip.h
bn_depr.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stdarg.h
bn_depr.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stddef.h
bn_div.o: ../../e_os.h ../../include/openssl/bio.h ../../include/openssl/bn.h
bn_div.o: ../../include/openssl/buffer.h ../../include/openssl/crypto.h
bn_div.o: ../../include/openssl/e_os2.h ../../include/openssl/err.h
bn_div.o: ../../include/openssl/lhash.h ../../include/openssl/opensslconf.h
bn_div.o: ../../include/openssl/opensslv.h ../../include/openssl/ossl_typ.h
bn_div.o: ../../include/openssl/safestack.h ../../include/openssl/stack.h
bn_div.o: ../../include/openssl/symhacks.h ../../ms/applink.c ../../ms/uplink.h
bn_div.o: ../cryptlib.h bn_div.c bn_lcl.h c:\mingw\include\_mingw.h
bn_div.o: c:\mingw\include\basetsd.h c:\mingw\include\errno.h
bn_div.o: c:\mingw\include\fcntl.h c:\mingw\include\io.h
bn_div.o: c:\mingw\include\malloc.h c:\mingw\include\poppack.h
bn_div.o: c:\mingw\include\pshpack4.h c:\mingw\include\stdio.h
bn_div.o: c:\mingw\include\stdlib.h c:\mingw\include\string.h
bn_div.o: c:\mingw\include\sys\types.h c:\mingw\include\winbase.h
bn_div.o: c:\mingw\include\wincon.h c:\mingw\include\windef.h
bn_div.o: c:\mingw\include\windows.h c:\mingw\include\winerror.h
bn_div.o: c:\mingw\include\wingdi.h c:\mingw\include\winnetwk.h
bn_div.o: c:\mingw\include\winnls.h c:\mingw\include\winnt.h
bn_div.o: c:\mingw\include\winreg.h c:\mingw\include\winsock2.h
bn_div.o: c:\mingw\include\winsvc.h c:\mingw\include\winuser.h
bn_div.o: c:\mingw\include\winver.h c:\mingw\include\ws2tcpip.h
bn_div.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stdarg.h
bn_div.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stddef.h
bn_err.o: ../../include/openssl/bio.h ../../include/openssl/bn.h
bn_err.o: ../../include/openssl/crypto.h ../../include/openssl/e_os2.h
bn_err.o: ../../include/openssl/err.h ../../include/openssl/lhash.h
bn_err.o: ../../include/openssl/opensslconf.h ../../include/openssl/opensslv.h
bn_err.o: ../../include/openssl/ossl_typ.h ../../include/openssl/safestack.h
bn_err.o: ../../include/openssl/stack.h ../../include/openssl/symhacks.h
bn_err.o: bn_err.c c:\mingw\include\_mingw.h c:\mingw\include\errno.h
bn_err.o: c:\mingw\include\stdio.h c:\mingw\include\stdlib.h
bn_err.o: c:\mingw\include\sys\types.h
bn_err.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stdarg.h
bn_err.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stddef.h
bn_exp.o: ../../e_os.h ../../include/openssl/bio.h ../../include/openssl/bn.h
bn_exp.o: ../../include/openssl/buffer.h ../../include/openssl/crypto.h
bn_exp.o: ../../include/openssl/e_os2.h ../../include/openssl/err.h
bn_exp.o: ../../include/openssl/lhash.h ../../include/openssl/opensslconf.h
bn_exp.o: ../../include/openssl/opensslv.h ../../include/openssl/ossl_typ.h
bn_exp.o: ../../include/openssl/safestack.h ../../include/openssl/stack.h
bn_exp.o: ../../include/openssl/symhacks.h ../../ms/applink.c ../../ms/uplink.h
bn_exp.o: ../cryptlib.h bn_exp.c bn_lcl.h c:\mingw\include\_mingw.h
bn_exp.o: c:\mingw\include\basetsd.h c:\mingw\include\errno.h
bn_exp.o: c:\mingw\include\fcntl.h c:\mingw\include\io.h
bn_exp.o: c:\mingw\include\malloc.h c:\mingw\include\poppack.h
bn_exp.o: c:\mingw\include\pshpack4.h c:\mingw\include\stdio.h
bn_exp.o: c:\mingw\include\stdlib.h c:\mingw\include\string.h
bn_exp.o: c:\mingw\include\sys\types.h c:\mingw\include\winbase.h
bn_exp.o: c:\mingw\include\wincon.h c:\mingw\include\windef.h
bn_exp.o: c:\mingw\include\windows.h c:\mingw\include\winerror.h
bn_exp.o: c:\mingw\include\wingdi.h c:\mingw\include\winnetwk.h
bn_exp.o: c:\mingw\include\winnls.h c:\mingw\include\winnt.h
bn_exp.o: c:\mingw\include\winreg.h c:\mingw\include\winsock2.h
bn_exp.o: c:\mingw\include\winsvc.h c:\mingw\include\winuser.h
bn_exp.o: c:\mingw\include\winver.h c:\mingw\include\ws2tcpip.h
bn_exp.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stdarg.h
bn_exp.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stddef.h
bn_exp2.o: ../../e_os.h ../../include/openssl/bio.h ../../include/openssl/bn.h
bn_exp2.o: ../../include/openssl/buffer.h ../../include/openssl/crypto.h
bn_exp2.o: ../../include/openssl/e_os2.h ../../include/openssl/err.h
bn_exp2.o: ../../include/openssl/lhash.h ../../include/openssl/opensslconf.h
bn_exp2.o: ../../include/openssl/opensslv.h ../../include/openssl/ossl_typ.h
bn_exp2.o: ../../include/openssl/safestack.h ../../include/openssl/stack.h
bn_exp2.o: ../../include/openssl/symhacks.h ../../ms/applink.c
bn_exp2.o: ../../ms/uplink.h ../cryptlib.h bn_exp2.c bn_lcl.h
bn_exp2.o: c:\mingw\include\_mingw.h c:\mingw\include\basetsd.h
bn_exp2.o: c:\mingw\include\errno.h c:\mingw\include\fcntl.h
bn_exp2.o: c:\mingw\include\io.h c:\mingw\include\malloc.h
bn_exp2.o: c:\mingw\include\poppack.h c:\mingw\include\pshpack4.h
bn_exp2.o: c:\mingw\include\stdio.h c:\mingw\include\stdlib.h
bn_exp2.o: c:\mingw\include\string.h c:\mingw\include\sys\types.h
bn_exp2.o: c:\mingw\include\winbase.h c:\mingw\include\wincon.h
bn_exp2.o: c:\mingw\include\windef.h c:\mingw\include\windows.h
bn_exp2.o: c:\mingw\include\winerror.h c:\mingw\include\wingdi.h
bn_exp2.o: c:\mingw\include\winnetwk.h c:\mingw\include\winnls.h
bn_exp2.o: c:\mingw\include\winnt.h c:\mingw\include\winreg.h
bn_exp2.o: c:\mingw\include\winsock2.h c:\mingw\include\winsvc.h
bn_exp2.o: c:\mingw\include\winuser.h c:\mingw\include\winver.h
bn_exp2.o: c:\mingw\include\ws2tcpip.h
bn_exp2.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stdarg.h
bn_exp2.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stddef.h
bn_gcd.o: ../../e_os.h ../../include/openssl/bio.h ../../include/openssl/bn.h
bn_gcd.o: ../../include/openssl/buffer.h ../../include/openssl/crypto.h
bn_gcd.o: ../../include/openssl/e_os2.h ../../include/openssl/err.h
bn_gcd.o: ../../include/openssl/lhash.h ../../include/openssl/opensslconf.h
bn_gcd.o: ../../include/openssl/opensslv.h ../../include/openssl/ossl_typ.h
bn_gcd.o: ../../include/openssl/safestack.h ../../include/openssl/stack.h
bn_gcd.o: ../../include/openssl/symhacks.h ../../ms/applink.c ../../ms/uplink.h
bn_gcd.o: ../cryptlib.h bn_gcd.c bn_lcl.h c:\mingw\include\_mingw.h
bn_gcd.o: c:\mingw\include\basetsd.h c:\mingw\include\errno.h
bn_gcd.o: c:\mingw\include\fcntl.h c:\mingw\include\io.h
bn_gcd.o: c:\mingw\include\malloc.h c:\mingw\include\poppack.h
bn_gcd.o: c:\mingw\include\pshpack4.h c:\mingw\include\stdio.h
bn_gcd.o: c:\mingw\include\stdlib.h c:\mingw\include\string.h
bn_gcd.o: c:\mingw\include\sys\types.h c:\mingw\include\winbase.h
bn_gcd.o: c:\mingw\include\wincon.h c:\mingw\include\windef.h
bn_gcd.o: c:\mingw\include\windows.h c:\mingw\include\winerror.h
bn_gcd.o: c:\mingw\include\wingdi.h c:\mingw\include\winnetwk.h
bn_gcd.o: c:\mingw\include\winnls.h c:\mingw\include\winnt.h
bn_gcd.o: c:\mingw\include\winreg.h c:\mingw\include\winsock2.h
bn_gcd.o: c:\mingw\include\winsvc.h c:\mingw\include\winuser.h
bn_gcd.o: c:\mingw\include\winver.h c:\mingw\include\ws2tcpip.h
bn_gcd.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stdarg.h
bn_gcd.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stddef.h
bn_gf2m.o: ../../e_os.h ../../include/openssl/bio.h ../../include/openssl/bn.h
bn_gf2m.o: ../../include/openssl/buffer.h ../../include/openssl/crypto.h
bn_gf2m.o: ../../include/openssl/e_os2.h ../../include/openssl/err.h
bn_gf2m.o: ../../include/openssl/lhash.h ../../include/openssl/opensslconf.h
bn_gf2m.o: ../../include/openssl/opensslv.h ../../include/openssl/ossl_typ.h
bn_gf2m.o: ../../include/openssl/safestack.h ../../include/openssl/stack.h
bn_gf2m.o: ../../include/openssl/symhacks.h ../../ms/applink.c
bn_gf2m.o: ../../ms/uplink.h ../cryptlib.h bn_gf2m.c bn_lcl.h
bn_gf2m.o: c:\mingw\include\_mingw.h c:\mingw\include\assert.h
bn_gf2m.o: c:\mingw\include\basetsd.h c:\mingw\include\errno.h
bn_gf2m.o: c:\mingw\include\fcntl.h c:\mingw\include\io.h
bn_gf2m.o: c:\mingw\include\limits.h c:\mingw\include\malloc.h
bn_gf2m.o: c:\mingw\include\poppack.h c:\mingw\include\pshpack4.h
bn_gf2m.o: c:\mingw\include\stdio.h c:\mingw\include\stdlib.h
bn_gf2m.o: c:\mingw\include\string.h c:\mingw\include\sys\types.h
bn_gf2m.o: c:\mingw\include\winbase.h c:\mingw\include\wincon.h
bn_gf2m.o: c:\mingw\include\windef.h c:\mingw\include\windows.h
bn_gf2m.o: c:\mingw\include\winerror.h c:\mingw\include\wingdi.h
bn_gf2m.o: c:\mingw\include\winnetwk.h c:\mingw\include\winnls.h
bn_gf2m.o: c:\mingw\include\winnt.h c:\mingw\include\winreg.h
bn_gf2m.o: c:\mingw\include\winsock2.h c:\mingw\include\winsvc.h
bn_gf2m.o: c:\mingw\include\winuser.h c:\mingw\include\winver.h
bn_gf2m.o: c:\mingw\include\ws2tcpip.h
bn_gf2m.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stdarg.h
bn_gf2m.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stddef.h
bn_kron.o: ../../e_os.h ../../include/openssl/bio.h ../../include/openssl/bn.h
bn_kron.o: ../../include/openssl/buffer.h ../../include/openssl/crypto.h
bn_kron.o: ../../include/openssl/e_os2.h ../../include/openssl/err.h
bn_kron.o: ../../include/openssl/lhash.h ../../include/openssl/opensslconf.h
bn_kron.o: ../../include/openssl/opensslv.h ../../include/openssl/ossl_typ.h
bn_kron.o: ../../include/openssl/safestack.h ../../include/openssl/stack.h
bn_kron.o: ../../include/openssl/symhacks.h ../../ms/applink.c
bn_kron.o: ../../ms/uplink.h ../cryptlib.h bn_kron.c bn_lcl.h
bn_kron.o: c:\mingw\include\_mingw.h c:\mingw\include\basetsd.h
bn_kron.o: c:\mingw\include\errno.h c:\mingw\include\fcntl.h
bn_kron.o: c:\mingw\include\io.h c:\mingw\include\malloc.h
bn_kron.o: c:\mingw\include\poppack.h c:\mingw\include\pshpack4.h
bn_kron.o: c:\mingw\include\stdio.h c:\mingw\include\stdlib.h
bn_kron.o: c:\mingw\include\string.h c:\mingw\include\sys\types.h
bn_kron.o: c:\mingw\include\winbase.h c:\mingw\include\wincon.h
bn_kron.o: c:\mingw\include\windef.h c:\mingw\include\windows.h
bn_kron.o: c:\mingw\include\winerror.h c:\mingw\include\wingdi.h
bn_kron.o: c:\mingw\include\winnetwk.h c:\mingw\include\winnls.h
bn_kron.o: c:\mingw\include\winnt.h c:\mingw\include\winreg.h
bn_kron.o: c:\mingw\include\winsock2.h c:\mingw\include\winsvc.h
bn_kron.o: c:\mingw\include\winuser.h c:\mingw\include\winver.h
bn_kron.o: c:\mingw\include\ws2tcpip.h
bn_kron.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stdarg.h
bn_kron.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stddef.h
bn_lib.o: ../../e_os.h ../../include/openssl/bio.h ../../include/openssl/bn.h
bn_lib.o: ../../include/openssl/buffer.h ../../include/openssl/crypto.h
bn_lib.o: ../../include/openssl/e_os2.h ../../include/openssl/err.h
bn_lib.o: ../../include/openssl/lhash.h ../../include/openssl/opensslconf.h
bn_lib.o: ../../include/openssl/opensslv.h ../../include/openssl/ossl_typ.h
bn_lib.o: ../../include/openssl/safestack.h ../../include/openssl/stack.h
bn_lib.o: ../../include/openssl/symhacks.h ../../ms/applink.c ../../ms/uplink.h
bn_lib.o: ../cryptlib.h bn_lcl.h bn_lib.c c:\mingw\include\_mingw.h
bn_lib.o: c:\mingw\include\assert.h c:\mingw\include\basetsd.h
bn_lib.o: c:\mingw\include\errno.h c:\mingw\include\fcntl.h
bn_lib.o: c:\mingw\include\io.h c:\mingw\include\limits.h
bn_lib.o: c:\mingw\include\malloc.h c:\mingw\include\poppack.h
bn_lib.o: c:\mingw\include\pshpack4.h c:\mingw\include\stdio.h
bn_lib.o: c:\mingw\include\stdlib.h c:\mingw\include\string.h
bn_lib.o: c:\mingw\include\sys\types.h c:\mingw\include\winbase.h
bn_lib.o: c:\mingw\include\wincon.h c:\mingw\include\windef.h
bn_lib.o: c:\mingw\include\windows.h c:\mingw\include\winerror.h
bn_lib.o: c:\mingw\include\wingdi.h c:\mingw\include\winnetwk.h
bn_lib.o: c:\mingw\include\winnls.h c:\mingw\include\winnt.h
bn_lib.o: c:\mingw\include\winreg.h c:\mingw\include\winsock2.h
bn_lib.o: c:\mingw\include\winsvc.h c:\mingw\include\winuser.h
bn_lib.o: c:\mingw\include\winver.h c:\mingw\include\ws2tcpip.h
bn_lib.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stdarg.h
bn_lib.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stddef.h
bn_mod.o: ../../e_os.h ../../include/openssl/bio.h ../../include/openssl/bn.h
bn_mod.o: ../../include/openssl/buffer.h ../../include/openssl/crypto.h
bn_mod.o: ../../include/openssl/e_os2.h ../../include/openssl/err.h
bn_mod.o: ../../include/openssl/lhash.h ../../include/openssl/opensslconf.h
bn_mod.o: ../../include/openssl/opensslv.h ../../include/openssl/ossl_typ.h
bn_mod.o: ../../include/openssl/safestack.h ../../include/openssl/stack.h
bn_mod.o: ../../include/openssl/symhacks.h ../../ms/applink.c ../../ms/uplink.h
bn_mod.o: ../cryptlib.h bn_lcl.h bn_mod.c c:\mingw\include\_mingw.h
bn_mod.o: c:\mingw\include\basetsd.h c:\mingw\include\errno.h
bn_mod.o: c:\mingw\include\fcntl.h c:\mingw\include\io.h
bn_mod.o: c:\mingw\include\malloc.h c:\mingw\include\poppack.h
bn_mod.o: c:\mingw\include\pshpack4.h c:\mingw\include\stdio.h
bn_mod.o: c:\mingw\include\stdlib.h c:\mingw\include\string.h
bn_mod.o: c:\mingw\include\sys\types.h c:\mingw\include\winbase.h
bn_mod.o: c:\mingw\include\wincon.h c:\mingw\include\windef.h
bn_mod.o: c:\mingw\include\windows.h c:\mingw\include\winerror.h
bn_mod.o: c:\mingw\include\wingdi.h c:\mingw\include\winnetwk.h
bn_mod.o: c:\mingw\include\winnls.h c:\mingw\include\winnt.h
bn_mod.o: c:\mingw\include\winreg.h c:\mingw\include\winsock2.h
bn_mod.o: c:\mingw\include\winsvc.h c:\mingw\include\winuser.h
bn_mod.o: c:\mingw\include\winver.h c:\mingw\include\ws2tcpip.h
bn_mod.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stdarg.h
bn_mod.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stddef.h
bn_mont.o: ../../e_os.h ../../include/openssl/bio.h ../../include/openssl/bn.h
bn_mont.o: ../../include/openssl/buffer.h ../../include/openssl/crypto.h
bn_mont.o: ../../include/openssl/e_os2.h ../../include/openssl/err.h
bn_mont.o: ../../include/openssl/lhash.h ../../include/openssl/opensslconf.h
bn_mont.o: ../../include/openssl/opensslv.h ../../include/openssl/ossl_typ.h
bn_mont.o: ../../include/openssl/safestack.h ../../include/openssl/stack.h
bn_mont.o: ../../include/openssl/symhacks.h ../../ms/applink.c
bn_mont.o: ../../ms/uplink.h ../cryptlib.h bn_lcl.h bn_mont.c
bn_mont.o: c:\mingw\include\_mingw.h c:\mingw\include\basetsd.h
bn_mont.o: c:\mingw\include\errno.h c:\mingw\include\fcntl.h
bn_mont.o: c:\mingw\include\io.h c:\mingw\include\malloc.h
bn_mont.o: c:\mingw\include\poppack.h c:\mingw\include\pshpack4.h
bn_mont.o: c:\mingw\include\stdio.h c:\mingw\include\stdlib.h
bn_mont.o: c:\mingw\include\string.h c:\mingw\include\sys\types.h
bn_mont.o: c:\mingw\include\winbase.h c:\mingw\include\wincon.h
bn_mont.o: c:\mingw\include\windef.h c:\mingw\include\windows.h
bn_mont.o: c:\mingw\include\winerror.h c:\mingw\include\wingdi.h
bn_mont.o: c:\mingw\include\winnetwk.h c:\mingw\include\winnls.h
bn_mont.o: c:\mingw\include\winnt.h c:\mingw\include\winreg.h
bn_mont.o: c:\mingw\include\winsock2.h c:\mingw\include\winsvc.h
bn_mont.o: c:\mingw\include\winuser.h c:\mingw\include\winver.h
bn_mont.o: c:\mingw\include\ws2tcpip.h
bn_mont.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stdarg.h
bn_mont.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stddef.h
bn_mpi.o: ../../e_os.h ../../include/openssl/bio.h ../../include/openssl/bn.h
bn_mpi.o: ../../include/openssl/buffer.h ../../include/openssl/crypto.h
bn_mpi.o: ../../include/openssl/e_os2.h ../../include/openssl/err.h
bn_mpi.o: ../../include/openssl/lhash.h ../../include/openssl/opensslconf.h
bn_mpi.o: ../../include/openssl/opensslv.h ../../include/openssl/ossl_typ.h
bn_mpi.o: ../../include/openssl/safestack.h ../../include/openssl/stack.h
bn_mpi.o: ../../include/openssl/symhacks.h ../../ms/applink.c ../../ms/uplink.h
bn_mpi.o: ../cryptlib.h bn_lcl.h bn_mpi.c c:\mingw\include\_mingw.h
bn_mpi.o: c:\mingw\include\basetsd.h c:\mingw\include\errno.h
bn_mpi.o: c:\mingw\include\fcntl.h c:\mingw\include\io.h
bn_mpi.o: c:\mingw\include\malloc.h c:\mingw\include\poppack.h
bn_mpi.o: c:\mingw\include\pshpack4.h c:\mingw\include\stdio.h
bn_mpi.o: c:\mingw\include\stdlib.h c:\mingw\include\string.h
bn_mpi.o: c:\mingw\include\sys\types.h c:\mingw\include\winbase.h
bn_mpi.o: c:\mingw\include\wincon.h c:\mingw\include\windef.h
bn_mpi.o: c:\mingw\include\windows.h c:\mingw\include\winerror.h
bn_mpi.o: c:\mingw\include\wingdi.h c:\mingw\include\winnetwk.h
bn_mpi.o: c:\mingw\include\winnls.h c:\mingw\include\winnt.h
bn_mpi.o: c:\mingw\include\winreg.h c:\mingw\include\winsock2.h
bn_mpi.o: c:\mingw\include\winsvc.h c:\mingw\include\winuser.h
bn_mpi.o: c:\mingw\include\winver.h c:\mingw\include\ws2tcpip.h
bn_mpi.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stdarg.h
bn_mpi.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stddef.h
bn_mul.o: ../../e_os.h ../../include/openssl/bio.h ../../include/openssl/bn.h
bn_mul.o: ../../include/openssl/buffer.h ../../include/openssl/crypto.h
bn_mul.o: ../../include/openssl/e_os2.h ../../include/openssl/err.h
bn_mul.o: ../../include/openssl/lhash.h ../../include/openssl/opensslconf.h
bn_mul.o: ../../include/openssl/opensslv.h ../../include/openssl/ossl_typ.h
bn_mul.o: ../../include/openssl/safestack.h ../../include/openssl/stack.h
bn_mul.o: ../../include/openssl/symhacks.h ../../ms/applink.c ../../ms/uplink.h
bn_mul.o: ../cryptlib.h bn_lcl.h bn_mul.c c:\mingw\include\_mingw.h
bn_mul.o: c:\mingw\include\assert.h c:\mingw\include\basetsd.h
bn_mul.o: c:\mingw\include\errno.h c:\mingw\include\fcntl.h
bn_mul.o: c:\mingw\include\io.h c:\mingw\include\malloc.h
bn_mul.o: c:\mingw\include\poppack.h c:\mingw\include\pshpack4.h
bn_mul.o: c:\mingw\include\stdio.h c:\mingw\include\stdlib.h
bn_mul.o: c:\mingw\include\string.h c:\mingw\include\sys\types.h
bn_mul.o: c:\mingw\include\winbase.h c:\mingw\include\wincon.h
bn_mul.o: c:\mingw\include\windef.h c:\mingw\include\windows.h
bn_mul.o: c:\mingw\include\winerror.h c:\mingw\include\wingdi.h
bn_mul.o: c:\mingw\include\winnetwk.h c:\mingw\include\winnls.h
bn_mul.o: c:\mingw\include\winnt.h c:\mingw\include\winreg.h
bn_mul.o: c:\mingw\include\winsock2.h c:\mingw\include\winsvc.h
bn_mul.o: c:\mingw\include\winuser.h c:\mingw\include\winver.h
bn_mul.o: c:\mingw\include\ws2tcpip.h
bn_mul.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stdarg.h
bn_mul.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stddef.h
bn_nist.o: ../../e_os.h ../../include/openssl/bio.h ../../include/openssl/bn.h
bn_nist.o: ../../include/openssl/buffer.h ../../include/openssl/crypto.h
bn_nist.o: ../../include/openssl/e_os2.h ../../include/openssl/err.h
bn_nist.o: ../../include/openssl/lhash.h ../../include/openssl/opensslconf.h
bn_nist.o: ../../include/openssl/opensslv.h ../../include/openssl/ossl_typ.h
bn_nist.o: ../../include/openssl/safestack.h ../../include/openssl/stack.h
bn_nist.o: ../../include/openssl/symhacks.h ../../ms/applink.c
bn_nist.o: ../../ms/uplink.h ../cryptlib.h bn_lcl.h bn_nist.c
bn_nist.o: c:\mingw\include\_mingw.h c:\mingw\include\basetsd.h
bn_nist.o: c:\mingw\include\errno.h c:\mingw\include\fcntl.h
bn_nist.o: c:\mingw\include\io.h c:\mingw\include\malloc.h
bn_nist.o: c:\mingw\include\poppack.h c:\mingw\include\pshpack4.h
bn_nist.o: c:\mingw\include\stdio.h c:\mingw\include\stdlib.h
bn_nist.o: c:\mingw\include\string.h c:\mingw\include\sys\types.h
bn_nist.o: c:\mingw\include\winbase.h c:\mingw\include\wincon.h
bn_nist.o: c:\mingw\include\windef.h c:\mingw\include\windows.h
bn_nist.o: c:\mingw\include\winerror.h c:\mingw\include\wingdi.h
bn_nist.o: c:\mingw\include\winnetwk.h c:\mingw\include\winnls.h
bn_nist.o: c:\mingw\include\winnt.h c:\mingw\include\winreg.h
bn_nist.o: c:\mingw\include\winsock2.h c:\mingw\include\winsvc.h
bn_nist.o: c:\mingw\include\winuser.h c:\mingw\include\winver.h
bn_nist.o: c:\mingw\include\ws2tcpip.h
bn_nist.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stdarg.h
bn_nist.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stddef.h
bn_prime.o: ../../e_os.h ../../include/openssl/bio.h ../../include/openssl/bn.h
bn_prime.o: ../../include/openssl/buffer.h ../../include/openssl/crypto.h
bn_prime.o: ../../include/openssl/e_os2.h ../../include/openssl/err.h
bn_prime.o: ../../include/openssl/lhash.h ../../include/openssl/opensslconf.h
bn_prime.o: ../../include/openssl/opensslv.h ../../include/openssl/ossl_typ.h
bn_prime.o: ../../include/openssl/rand.h ../../include/openssl/safestack.h
bn_prime.o: ../../include/openssl/stack.h ../../include/openssl/symhacks.h
bn_prime.o: ../../ms/applink.c ../../ms/uplink.h ../cryptlib.h bn_lcl.h
bn_prime.o: bn_prime.c bn_prime.h c:\mingw\include\_mingw.h
bn_prime.o: c:\mingw\include\basetsd.h c:\mingw\include\errno.h
bn_prime.o: c:\mingw\include\fcntl.h c:\mingw\include\io.h
bn_prime.o: c:\mingw\include\malloc.h c:\mingw\include\poppack.h
bn_prime.o: c:\mingw\include\pshpack4.h c:\mingw\include\stdio.h
bn_prime.o: c:\mingw\include\stdlib.h c:\mingw\include\string.h
bn_prime.o: c:\mingw\include\sys\types.h c:\mingw\include\time.h
bn_prime.o: c:\mingw\include\winbase.h c:\mingw\include\wincon.h
bn_prime.o: c:\mingw\include\windef.h c:\mingw\include\windows.h
bn_prime.o: c:\mingw\include\winerror.h c:\mingw\include\wingdi.h
bn_prime.o: c:\mingw\include\winnetwk.h c:\mingw\include\winnls.h
bn_prime.o: c:\mingw\include\winnt.h c:\mingw\include\winreg.h
bn_prime.o: c:\mingw\include\winsock2.h c:\mingw\include\winsvc.h
bn_prime.o: c:\mingw\include\winuser.h c:\mingw\include\winver.h
bn_prime.o: c:\mingw\include\ws2tcpip.h
bn_prime.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stdarg.h
bn_prime.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stddef.h
bn_print.o: ../../e_os.h ../../include/openssl/bio.h ../../include/openssl/bn.h
bn_print.o: ../../include/openssl/buffer.h ../../include/openssl/crypto.h
bn_print.o: ../../include/openssl/e_os2.h ../../include/openssl/err.h
bn_print.o: ../../include/openssl/lhash.h ../../include/openssl/opensslconf.h
bn_print.o: ../../include/openssl/opensslv.h ../../include/openssl/ossl_typ.h
bn_print.o: ../../include/openssl/safestack.h ../../include/openssl/stack.h
bn_print.o: ../../include/openssl/symhacks.h ../../ms/applink.c
bn_print.o: ../../ms/uplink.h ../cryptlib.h bn_lcl.h bn_print.c
bn_print.o: c:\mingw\include\_mingw.h c:\mingw\include\basetsd.h
bn_print.o: c:\mingw\include\ctype.h c:\mingw\include\errno.h
bn_print.o: c:\mingw\include\fcntl.h c:\mingw\include\io.h
bn_print.o: c:\mingw\include\malloc.h c:\mingw\include\poppack.h
bn_print.o: c:\mingw\include\pshpack4.h c:\mingw\include\stdio.h
bn_print.o: c:\mingw\include\stdlib.h c:\mingw\include\string.h
bn_print.o: c:\mingw\include\sys\types.h c:\mingw\include\winbase.h
bn_print.o: c:\mingw\include\wincon.h c:\mingw\include\windef.h
bn_print.o: c:\mingw\include\windows.h c:\mingw\include\winerror.h
bn_print.o: c:\mingw\include\wingdi.h c:\mingw\include\winnetwk.h
bn_print.o: c:\mingw\include\winnls.h c:\mingw\include\winnt.h
bn_print.o: c:\mingw\include\winreg.h c:\mingw\include\winsock2.h
bn_print.o: c:\mingw\include\winsvc.h c:\mingw\include\winuser.h
bn_print.o: c:\mingw\include\winver.h c:\mingw\include\ws2tcpip.h
bn_print.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stdarg.h
bn_print.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stddef.h
bn_rand.o: ../../e_os.h ../../include/openssl/bio.h ../../include/openssl/bn.h
bn_rand.o: ../../include/openssl/buffer.h ../../include/openssl/crypto.h
bn_rand.o: ../../include/openssl/e_os2.h ../../include/openssl/err.h
bn_rand.o: ../../include/openssl/lhash.h ../../include/openssl/opensslconf.h
bn_rand.o: ../../include/openssl/opensslv.h ../../include/openssl/ossl_typ.h
bn_rand.o: ../../include/openssl/rand.h ../../include/openssl/safestack.h
bn_rand.o: ../../include/openssl/stack.h ../../include/openssl/symhacks.h
bn_rand.o: ../../ms/applink.c ../../ms/uplink.h ../cryptlib.h bn_lcl.h
bn_rand.o: bn_rand.c c:\mingw\include\_mingw.h c:\mingw\include\basetsd.h
bn_rand.o: c:\mingw\include\errno.h c:\mingw\include\fcntl.h
bn_rand.o: c:\mingw\include\io.h c:\mingw\include\malloc.h
bn_rand.o: c:\mingw\include\poppack.h c:\mingw\include\pshpack4.h
bn_rand.o: c:\mingw\include\stdio.h c:\mingw\include\stdlib.h
bn_rand.o: c:\mingw\include\string.h c:\mingw\include\sys\types.h
bn_rand.o: c:\mingw\include\time.h c:\mingw\include\winbase.h
bn_rand.o: c:\mingw\include\wincon.h c:\mingw\include\windef.h
bn_rand.o: c:\mingw\include\windows.h c:\mingw\include\winerror.h
bn_rand.o: c:\mingw\include\wingdi.h c:\mingw\include\winnetwk.h
bn_rand.o: c:\mingw\include\winnls.h c:\mingw\include\winnt.h
bn_rand.o: c:\mingw\include\winreg.h c:\mingw\include\winsock2.h
bn_rand.o: c:\mingw\include\winsvc.h c:\mingw\include\winuser.h
bn_rand.o: c:\mingw\include\winver.h c:\mingw\include\ws2tcpip.h
bn_rand.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stdarg.h
bn_rand.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stddef.h
bn_recp.o: ../../e_os.h ../../include/openssl/bio.h ../../include/openssl/bn.h
bn_recp.o: ../../include/openssl/buffer.h ../../include/openssl/crypto.h
bn_recp.o: ../../include/openssl/e_os2.h ../../include/openssl/err.h
bn_recp.o: ../../include/openssl/lhash.h ../../include/openssl/opensslconf.h
bn_recp.o: ../../include/openssl/opensslv.h ../../include/openssl/ossl_typ.h
bn_recp.o: ../../include/openssl/safestack.h ../../include/openssl/stack.h
bn_recp.o: ../../include/openssl/symhacks.h ../../ms/applink.c
bn_recp.o: ../../ms/uplink.h ../cryptlib.h bn_lcl.h bn_recp.c
bn_recp.o: c:\mingw\include\_mingw.h c:\mingw\include\basetsd.h
bn_recp.o: c:\mingw\include\errno.h c:\mingw\include\fcntl.h
bn_recp.o: c:\mingw\include\io.h c:\mingw\include\malloc.h
bn_recp.o: c:\mingw\include\poppack.h c:\mingw\include\pshpack4.h
bn_recp.o: c:\mingw\include\stdio.h c:\mingw\include\stdlib.h
bn_recp.o: c:\mingw\include\string.h c:\mingw\include\sys\types.h
bn_recp.o: c:\mingw\include\winbase.h c:\mingw\include\wincon.h
bn_recp.o: c:\mingw\include\windef.h c:\mingw\include\windows.h
bn_recp.o: c:\mingw\include\winerror.h c:\mingw\include\wingdi.h
bn_recp.o: c:\mingw\include\winnetwk.h c:\mingw\include\winnls.h
bn_recp.o: c:\mingw\include\winnt.h c:\mingw\include\winreg.h
bn_recp.o: c:\mingw\include\winsock2.h c:\mingw\include\winsvc.h
bn_recp.o: c:\mingw\include\winuser.h c:\mingw\include\winver.h
bn_recp.o: c:\mingw\include\ws2tcpip.h
bn_recp.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stdarg.h
bn_recp.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stddef.h
bn_shift.o: ../../e_os.h ../../include/openssl/bio.h ../../include/openssl/bn.h
bn_shift.o: ../../include/openssl/buffer.h ../../include/openssl/crypto.h
bn_shift.o: ../../include/openssl/e_os2.h ../../include/openssl/err.h
bn_shift.o: ../../include/openssl/lhash.h ../../include/openssl/opensslconf.h
bn_shift.o: ../../include/openssl/opensslv.h ../../include/openssl/ossl_typ.h
bn_shift.o: ../../include/openssl/safestack.h ../../include/openssl/stack.h
bn_shift.o: ../../include/openssl/symhacks.h ../../ms/applink.c
bn_shift.o: ../../ms/uplink.h ../cryptlib.h bn_lcl.h bn_shift.c
bn_shift.o: c:\mingw\include\_mingw.h c:\mingw\include\basetsd.h
bn_shift.o: c:\mingw\include\errno.h c:\mingw\include\fcntl.h
bn_shift.o: c:\mingw\include\io.h c:\mingw\include\malloc.h
bn_shift.o: c:\mingw\include\poppack.h c:\mingw\include\pshpack4.h
bn_shift.o: c:\mingw\include\stdio.h c:\mingw\include\stdlib.h
bn_shift.o: c:\mingw\include\string.h c:\mingw\include\sys\types.h
bn_shift.o: c:\mingw\include\winbase.h c:\mingw\include\wincon.h
bn_shift.o: c:\mingw\include\windef.h c:\mingw\include\windows.h
bn_shift.o: c:\mingw\include\winerror.h c:\mingw\include\wingdi.h
bn_shift.o: c:\mingw\include\winnetwk.h c:\mingw\include\winnls.h
bn_shift.o: c:\mingw\include\winnt.h c:\mingw\include\winreg.h
bn_shift.o: c:\mingw\include\winsock2.h c:\mingw\include\winsvc.h
bn_shift.o: c:\mingw\include\winuser.h c:\mingw\include\winver.h
bn_shift.o: c:\mingw\include\ws2tcpip.h
bn_shift.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stdarg.h
bn_shift.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stddef.h
bn_sqr.o: ../../e_os.h ../../include/openssl/bio.h ../../include/openssl/bn.h
bn_sqr.o: ../../include/openssl/buffer.h ../../include/openssl/crypto.h
bn_sqr.o: ../../include/openssl/e_os2.h ../../include/openssl/err.h
bn_sqr.o: ../../include/openssl/lhash.h ../../include/openssl/opensslconf.h
bn_sqr.o: ../../include/openssl/opensslv.h ../../include/openssl/ossl_typ.h
bn_sqr.o: ../../include/openssl/safestack.h ../../include/openssl/stack.h
bn_sqr.o: ../../include/openssl/symhacks.h ../../ms/applink.c ../../ms/uplink.h
bn_sqr.o: ../cryptlib.h bn_lcl.h bn_sqr.c c:\mingw\include\_mingw.h
bn_sqr.o: c:\mingw\include\basetsd.h c:\mingw\include\errno.h
bn_sqr.o: c:\mingw\include\fcntl.h c:\mingw\include\io.h
bn_sqr.o: c:\mingw\include\malloc.h c:\mingw\include\poppack.h
bn_sqr.o: c:\mingw\include\pshpack4.h c:\mingw\include\stdio.h
bn_sqr.o: c:\mingw\include\stdlib.h c:\mingw\include\string.h
bn_sqr.o: c:\mingw\include\sys\types.h c:\mingw\include\winbase.h
bn_sqr.o: c:\mingw\include\wincon.h c:\mingw\include\windef.h
bn_sqr.o: c:\mingw\include\windows.h c:\mingw\include\winerror.h
bn_sqr.o: c:\mingw\include\wingdi.h c:\mingw\include\winnetwk.h
bn_sqr.o: c:\mingw\include\winnls.h c:\mingw\include\winnt.h
bn_sqr.o: c:\mingw\include\winreg.h c:\mingw\include\winsock2.h
bn_sqr.o: c:\mingw\include\winsvc.h c:\mingw\include\winuser.h
bn_sqr.o: c:\mingw\include\winver.h c:\mingw\include\ws2tcpip.h
bn_sqr.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stdarg.h
bn_sqr.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stddef.h
bn_sqrt.o: ../../e_os.h ../../include/openssl/bio.h ../../include/openssl/bn.h
bn_sqrt.o: ../../include/openssl/buffer.h ../../include/openssl/crypto.h
bn_sqrt.o: ../../include/openssl/e_os2.h ../../include/openssl/err.h
bn_sqrt.o: ../../include/openssl/lhash.h ../../include/openssl/opensslconf.h
bn_sqrt.o: ../../include/openssl/opensslv.h ../../include/openssl/ossl_typ.h
bn_sqrt.o: ../../include/openssl/safestack.h ../../include/openssl/stack.h
bn_sqrt.o: ../../include/openssl/symhacks.h ../../ms/applink.c
bn_sqrt.o: ../../ms/uplink.h ../cryptlib.h bn_lcl.h bn_sqrt.c
bn_sqrt.o: c:\mingw\include\_mingw.h c:\mingw\include\basetsd.h
bn_sqrt.o: c:\mingw\include\errno.h c:\mingw\include\fcntl.h
bn_sqrt.o: c:\mingw\include\io.h c:\mingw\include\malloc.h
bn_sqrt.o: c:\mingw\include\poppack.h c:\mingw\include\pshpack4.h
bn_sqrt.o: c:\mingw\include\stdio.h c:\mingw\include\stdlib.h
bn_sqrt.o: c:\mingw\include\string.h c:\mingw\include\sys\types.h
bn_sqrt.o: c:\mingw\include\winbase.h c:\mingw\include\wincon.h
bn_sqrt.o: c:\mingw\include\windef.h c:\mingw\include\windows.h
bn_sqrt.o: c:\mingw\include\winerror.h c:\mingw\include\wingdi.h
bn_sqrt.o: c:\mingw\include\winnetwk.h c:\mingw\include\winnls.h
bn_sqrt.o: c:\mingw\include\winnt.h c:\mingw\include\winreg.h
bn_sqrt.o: c:\mingw\include\winsock2.h c:\mingw\include\winsvc.h
bn_sqrt.o: c:\mingw\include\winuser.h c:\mingw\include\winver.h
bn_sqrt.o: c:\mingw\include\ws2tcpip.h
bn_sqrt.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stdarg.h
bn_sqrt.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stddef.h
bn_word.o: ../../e_os.h ../../include/openssl/bio.h ../../include/openssl/bn.h
bn_word.o: ../../include/openssl/buffer.h ../../include/openssl/crypto.h
bn_word.o: ../../include/openssl/e_os2.h ../../include/openssl/err.h
bn_word.o: ../../include/openssl/lhash.h ../../include/openssl/opensslconf.h
bn_word.o: ../../include/openssl/opensslv.h ../../include/openssl/ossl_typ.h
bn_word.o: ../../include/openssl/safestack.h ../../include/openssl/stack.h
bn_word.o: ../../include/openssl/symhacks.h ../../ms/applink.c
bn_word.o: ../../ms/uplink.h ../cryptlib.h bn_lcl.h bn_word.c
bn_word.o: c:\mingw\include\_mingw.h c:\mingw\include\basetsd.h
bn_word.o: c:\mingw\include\errno.h c:\mingw\include\fcntl.h
bn_word.o: c:\mingw\include\io.h c:\mingw\include\malloc.h
bn_word.o: c:\mingw\include\poppack.h c:\mingw\include\pshpack4.h
bn_word.o: c:\mingw\include\stdio.h c:\mingw\include\stdlib.h
bn_word.o: c:\mingw\include\string.h c:\mingw\include\sys\types.h
bn_word.o: c:\mingw\include\winbase.h c:\mingw\include\wincon.h
bn_word.o: c:\mingw\include\windef.h c:\mingw\include\windows.h
bn_word.o: c:\mingw\include\winerror.h c:\mingw\include\wingdi.h
bn_word.o: c:\mingw\include\winnetwk.h c:\mingw\include\winnls.h
bn_word.o: c:\mingw\include\winnt.h c:\mingw\include\winreg.h
bn_word.o: c:\mingw\include\winsock2.h c:\mingw\include\winsvc.h
bn_word.o: c:\mingw\include\winuser.h c:\mingw\include\winver.h
bn_word.o: c:\mingw\include\ws2tcpip.h
bn_word.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stdarg.h
bn_word.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stddef.h
bn_x931p.o: ../../include/openssl/bn.h ../../include/openssl/crypto.h
bn_x931p.o: ../../include/openssl/e_os2.h ../../include/openssl/opensslconf.h
bn_x931p.o: ../../include/openssl/opensslv.h ../../include/openssl/ossl_typ.h
bn_x931p.o: ../../include/openssl/safestack.h ../../include/openssl/stack.h
bn_x931p.o: ../../include/openssl/symhacks.h bn_x931p.c
bn_x931p.o: c:\mingw\include\_mingw.h c:\mingw\include\stdio.h
bn_x931p.o: c:\mingw\include\stdlib.h c:\mingw\include\sys\types.h
bn_x931p.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stdarg.h
bn_x931p.o: c:\mingw\lib\gcc\mingw32\4.8.1\include\stddef.h
