#ifndef MK1MF_BUILD
    /* auto-generated by util/mkbuildinf.pl for crypto/cversion.c */
    #define CFLAGS cflags
    /*
     * Generate CFLAGS as an array of individual characters. This is a
     * workaround for the situation where CFLAGS gets too long for a C90 string
     * literal
     */
    static const char cflags[] = {
        'c','o','m','p','i','l','e','r',':',' ','g','c','c',' ','-','I','.',' ',
        '-','I','.','.',' ','-','I','.','.','/','i','n','c','l','u','d','e',' ',
        ' ','-','D','O','P','E','N','S','S','L','_','T','H','R','E','A','D','S',
        ' ','-','D','_','M','T',' ','-','D','D','S','O','_','W','I','N','3','2',
        ' ','-','D','L','_','E','N','D','I','A','N',' ','-','D','W','I','N','3',
        '2','_','L','E','A','N','_','A','N','D','_','M','E','A','N',' ','-','f',
        'o','m','i','t','-','f','r','a','m','e','-','p','o','i','n','t','e','r',
        ' ','-','O','3',' ','-','m','a','r','c','h','=','i','4','8','6',' ','-',
        'W','a','l','l','\0'
    };
    #define PLATFORM "platform: mingw"
    #define DATE "built on: Tue Jun 30 17:43:02 2015"
#endif
